config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }
  #ゲストログイン
  devise_scope :user do
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  scope module: :user do
    root to: "homes#top"
    get 'about' => 'homes#about'
    get 'genre_search', to: 'searches#genre_search', as: :genre_search
    get "search" => "searches#search"

    # 投稿
    get 'posts/new', to: 'posts#new', as: 'new_post'
    post 'posts', to: 'posts#create'
    get 'posts' => 'posts#index'
    get 'posts/:id', to: 'posts#show', as: 'post'
    get 'posts/:id/edit', to: 'posts#edit', as: 'edit_post'
    delete 'posts/:id', to: 'posts#destroy', as: 'delete_post'
    
    # コメント・いいね機能
    resources :posts do
      resources :comments, only: [:create, :destroy, :edit, :update] do
        member do
          patch :mark_best_answer
          patch :unmark_best_answer
        end
      end
      resource :likes, only: [:create, :destroy]
    end

    resources :likes, only: [:index]
    
    # 通知機能
    resources :notifications, only: [:index] do
      collection do
        patch :mark_as_read
        patch :mark_all_as_read
      end
    end

    # ジャンル
    resources :genres, only: [:index,:create]

    # ユーザー
    get 'users' => 'users#index'
    get '/my_page', to: 'users#my_page', as: :my_page
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/:id/edit' => 'users#edit', as: 'users_edit'
    get 'users/:id', to: 'users#show', as: 'user'
    patch 'users/:id' => 'users#update'



  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    get 'admin', to: 'admin/sessions#new', as: :admin_session_new
  end

  namespace :admin do
    resources :genres, only: [:index,:edit,:update, :destroy]
    resources :posts, only: [:index,:show,:destroy]
    resources :users, only: [:index,:show,:edit,:update]

    get "search" => "searches#search"
    
    resources :posts do
      resources :comments, only: [:destroy]
    end
    
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  validates :name, presence: true, uniqueness: true, length: { maximum: 15 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = case params[:sort]
              when 'posts_count'
                Genre.left_joins(:posts).group(:id).order('COUNT(posts.id) DESC')
              when 'name'
                Genre.order(:name)
              else
                Genre.all
              end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: 'ジャンル名が編集されました'
    else
      render :edit
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path, notice: 'ジャンルを削除しました。'
  end
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @genre = Genre.new
  end
  
  def index
    @genre = Genre.new
    @genres = case params[:sort]
              when 'name'
                Genre.order(:name)
              else
                Genre.left_joins(:posts).group(:id).order('COUNT(posts.id) DESC')
              end
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      render json: { id: @genre.id, name: @genre.name }
    else
      render json: { errors: @genre.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genres_path, notice: "変更を保存しました。"
    else
      render 'edit'
    end  
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def init_sidebar
    @posts = Post.where(is_active: true)
    @genres = Genre.all
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container mt-5">
  <h2 class="fw-light">ジャンル名編集</h2>
  <hr class="heading-line mb-4">

  <%= form_with(model: [:admin, @genre], local: true) do |form| %>
    <% if @genre.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">エラーがあります：</h4>
        <ul>
          <% @genre.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, 'ジャンル名', class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control', value: @genre.name %>
    </div>

    <div class="d-flex justify-content-end">
      <%= link_to 'キャンセル', admin_genres_path, class: 'btn btn-secondary me-2' %>
      <%= form.submit '更新する', class: 'btn btn-primary me-2' %>
      <%= link_to '削除', admin_genre_path(@genre), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-danger', id: 'delete-genre-btn' %>
    </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="py-5 text-center container">
  <h2 class="fw-light">ジャンル一覧</h2>
  <hr class="heading-line mb-4">
  <div class="d-flex justify-content-end mb-4">
    <div class="btn-group" role="group" aria-label="Sort options">
      <%= link_to '投稿数順', admin_genres_path(sort: 'posts_count'), class: "btn btn-outline-primary" %>
      <%= link_to '名前順', admin_genres_path(sort: 'name'), class: "btn btn-outline-primary" %>
    </div>
  </div>

  <div class="row mt-4">
    <% @genres.each do |genre| %>
      <div class="col-sm-6 col-md-4 col-lg-3 mb-2">
        <div class="card shadow-sm pt-2">
          <h5 class="card-title">
            <%= link_to truncate(genre.name, length: 10), edit_admin_genre_path(genre), class: "text-dark" %>
            <span class="badge bg-primary rounded-pill"><%= genre.posts.count %></span>
          </h5>
        </div>
      </div>
    <% end %>
  </div>
</div>