config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }
  #ゲストログイン
  devise_scope :user do
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  scope module: :user do
    root to: "homes#top"
    get 'about' => 'homes#about'
    get 'genre_search', to: 'searches#genre_search', as: :genre_search
    get "search" => "searches#search"

    # 投稿
    get 'posts/new', to: 'posts#new', as: 'new_post'
    post 'posts', to: 'posts#create'
    get 'posts' => 'posts#index'
    get 'posts/:id', to: 'posts#show', as: 'post'
    get 'posts/:id/edit', to: 'posts#edit', as: 'edit_post'
    delete 'posts/:id', to: 'posts#destroy', as: 'delete_post'
    
    # コメント・いいね機能
    resources :posts do
      resources :comments, only: [:create, :destroy, :edit, :update] do
        member do
          patch :mark_best_answer
          patch :unmark_best_answer
        end
      end
      resource :likes, only: [:create, :destroy]
    end

    resources :likes, only: [:index]
    
    # 通知機能
    resources :notifications, only: [:index] do
      collection do
        patch :mark_as_read
        patch :mark_all_as_read
      end
    end

    # ジャンル
    resources :genres, only: [:index,:create]

    # ユーザー
    get 'users' => 'users#index'
    get '/my_page', to: 'users#my_page', as: :my_page
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/:id/edit' => 'users#edit', as: 'users_edit'
    get 'users/:id', to: 'users#show', as: 'user'
    patch 'users/:id' => 'users#update'



  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    get 'admin', to: 'admin/sessions#new', as: :admin_session_new
  end

  namespace :admin do
    resources :genres, only: [:index,:edit,:update, :destroy]
    resources :posts, only: [:index,:show,:destroy]
    resources :users, only: [:index,:show,:edit,:update]

    get "search" => "searches#search"
    
    resources :posts do
      resources :comments, only: [:destroy]
    end
    
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :check_guest_user, only: [:create]
  

  
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.best_answer
      @comment.update(best_answer: false)
    end

    @comment.destroy
    redirect_to admin_post_path(@post), notice: "コメントを削除しました。"
  end


  private

  def comment_params
     params.require(:comment).permit(:content)
  end
  
 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end  
  end
  
  def user_params
  params.require(:user).permit(:name, :email, :is_active)
  end
  
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_guest_user, only: [:create]
  before_action :set_post
  before_action :set_comment, only: [:destroy, :edit, :update, :mark_best_answer, :unmark_best_answer]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  
  
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      @post.create_notification_by(current_user)
      respond_to do |format|
        format.html { redirect_to @post, notice: 'コメントが追加されました。' }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'posts/show', alert: 'コメントの追加に失敗しました。' }
        format.js { render 'error.js.erb' }
      end
    end
  end
  
  def edit
  end
  
  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post), notice: 'コメントが更新されました'
    else
      render :edit
    end
  end
  
  def destroy
    @comment.destroy
    respond_to do |format|
      format.js
    end
  end

  def mark_best_answer
    @post.comments.update_all(best_answer: false) # 既存のベストアンサーを解除
    @comment.update(best_answer: true)
    redirect_to @post, notice: 'ベストアンサーを設定しました。'
  end

  def unmark_best_answer
    @comment.update(best_answer: false)
    redirect_to @post, notice: 'ベストアンサーを解除しました。'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
  
  def check_guest_user
    if current_user.email == "guest@example.com"
      redirect_to post_path(@post), alert: "ゲストユーザーはコメントできません。"
    end
  end
  
  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def authorize_user
    unless current_user == @comment.user
      redirect_to post_path(@post), alert: '他のユーザーのコメントを操作する権限がありません。'
    end
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @genre = Genre.new
  end
  
  def index
    @genre = Genre.new
    @genres = case params[:sort]
              when 'name'
                Genre.order(:name)
              else
                Genre.left_joins(:posts).group(:id).order('COUNT(posts.id) DESC')
              end
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      render json: { id: @genre.id, name: @genre.name }
    else
      render json: { errors: @genre.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genres_path, notice: "変更を保存しました。"
    else
      render 'edit'
    end  
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def init_sidebar
    @posts = Post.where(is_active: true)
    @genres = Genre.all
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @genres = Genre.all
    @posts = Post.order(created_at: :desc).limit(12)
  end

  def about
  end
end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_guest_user, only: [:create, :destroy]

  def create
    @action_name = params[:action_name]
    @post = Post.find(params[:post_id])
    @likes= current_user.likes.create(post_id: @post.id)
    #redirect_back(fallback_location: "/posts")
  end

  def destroy
    @action_name = params[:action_name]
    @post = Post.find(params[:post_id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy 
    #redirect_back(fallback_location: "/posts")
  end

  def index
    @likes = current_user.likes.includes(:post)
    @posts = Post.where(id: @likes.pluck(:post_id)).order(created_at: :desc).page(params[:page]).per(12)
  end
  
  private

  def check_guest_user
    if current_user.email == "guest@example.com"
      redirect_back fallback_location: root_path, alert: "ゲストユーザーはいいねを押せません。"
    end
  end
  
  
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.passive_notifications.unread.order(created_at: :desc).page(params[:page]).per(10)
  end

  def mark_all_as_read
    current_user.notifications.update_all(read: true)
    redirect_to notifications_path, notice: 'すべての通知を既読にしました。'
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_post, only: [:show, :edit, :update, :destroy]
  before_action :check_guest_user, only: [:new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
    @genres = Genre.all
  end

  def create
    @post = current_user.posts.build(post_params)
    if params[:post][:new_genre_name].present?
      genre = Genre.find_or_create_by(name: params[:post][:new_genre_name])
      @post.genre = genre
    end
    if @post.save
      flash[:notice] = "投稿が作成されました。"
      redirect_to @post
    else
      flash.now[:alert] = "投稿に失敗しました。"
      @genres = Genre.all
      render 'new'
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :asc)
    @user = current_user
  end

  def edit
    @genres = Genre.all
  end

  def index
    @genres = Genre.left_joins(:posts).group(:id).order('COUNT(posts.id) DESC')
    @post_all = Post.all
  
    if params[:latest]
      @posts = Post.latest.page(params[:page]).per(12)
    elsif params[:old]
      @posts = Post.old.page(params[:page]).per(12)
    elsif params[:most_liked]
      @posts = Kaminari.paginate_array(Post.most_liked).page(params[:page]).per(12)
    elsif params[:best_answer] == "true"
      @posts = Post.joins(:comments).where(comments: { best_answer: true }).distinct.order(created_at: :desc).page(params[:page]).per(12)
    elsif params[:best_answer] == "false"
      @posts = Post.where.not(id: Comment.select(:post_id).where(best_answer: true)).order(created_at: :desc).page(params[:page]).per(12)
    else
      @posts = Post.latest.page(params[:page]).per(12)
    end
  end

  def update
    if @post.update(post_params)
      handle_new_genre_name
      flash[:notice] = "更新しました。"
      redirect_to post_path(@post)
    else
      flash.now[:alert] = "更新に失敗しました。"
      @genres = Genre.all
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, notice: "投稿を削除しました"
    else
      flash[:alert] = "削除に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def check_guest_user
    if current_user.email == "guest@example.com"
      redirect_to posts_path, alert: "ゲストユーザーは新規投稿を作成できません。"
    end
  end

  def ensure_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :introduction, :genre_id, :image, :new_genre_name)
  end

  def handle_new_genre_name
    if post_params[:new_genre_name].present?
      genre = Genre.find_or_create_by(name: post_params[:new_genre_name])
      @post.genre = genre
      @post.save
    end
  end

  def correct_user
    unless @post.user == current_user
      redirect_back(fallback_location: root_path, alert: '他のユーザーの投稿を編集または削除する権限がありません。')
    end
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController

  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

  def after_sign_up_path_for(resource)
    my_page_path
  end

  def after_update_path_for(resource)
    my_page_path
  end

  # ユーザー登録時の許可するパラメーター
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end

  # ユーザー情報更新時の許可するパラメーター
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation, :current_password])
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to my_page_path(@user), notice: 'ユーザー情報が更新されました。'
    else
       redirect_to users_edit_path(@user)
      # render "/users/#{@user.id}/edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :profile_image, :introduction )
  end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  

  def genre_search
    @genre = Genre.find(params[:genre_id])
    @genre_id = params[:genre_id]
    @posts = Post.where(genre_id: @genre_id).page(params[:page]).per(12) 
    @genres = Genre.left_joins(:posts).group(:id).order('COUNT(posts.id) DESC')
    @posts_all = @genre.posts
    
    @posts = Post.where(genre_id: @genre_id)

    if params[:latest]
      @posts = @genre.posts.latest.page(params[:page]).per(12)
    elsif params[:old]
      @posts = @genre.posts.old.page(params[:page]).per(12)
    elsif params[:most_liked]
      @posts = Kaminari.paginate_array(@genre.posts.most_liked).page(params[:page]).per(12)
    elsif params[:best_answer] == "true"
      @posts = @genre.posts.joins(:comments).where(comments: { best_answer: true }).distinct.page(params[:page]).per(12)
    elsif params[:best_answer] == "false"
      @posts = @genre.posts.where.not(id: Comment.select(:post_id).where(best_answer: true)).order(created_at: :desc).page(params[:page]).per(12)
    else
      @posts = @genre.posts.latest.page(params[:page]).per(12)
    end

  end

  def search
    @genres = case params[:sort]
              when 'name'
                Genre.order(:name)
              else
                Genre.left_joins(:posts).group(:id).order('COUNT(posts.id) DESC')
              end
    @keyword = params[:keyword]
  
    if @keyword.present?
      @results = Post.search_for(@keyword).order(created_at: :desc).page(params[:page]).per(12)
      @results_all = Post.search_for(@keyword)
      @posts = @results
    else
      @results = []
      @results_all = Post.none  # キーワードがない場合に @results_all を空のコレクションに設定
      @posts = Post.none.page(params[:page]).per(12)
    end
  
    render 'user/searches/search'
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]

  def after_sign_in_path_for(resource)
    my_page_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  
  #ゲストサインイン
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to my_page_path, notice: "guestuserでログインしました。"
  end
  
  private
  #退会しているかいないか
  def user_state
    # 【処理内容1】 入力されたemailからアカウントを1件取得
    user = User.find_by(email: params[:user][:email])
    # 【処理内容2】 アカウントを取得できなかった場合、このメソッドを終了する
    return if user.nil?
    # 【処理内容3】 取得したアカウントのパスワードと入力されたパスワードが一致していない場合、このメソッドを終了する
    return unless user.valid_password?(params[:user][:password])
    unless user.is_active
      flash[:alert] = "すでに退会されているアカウントです。管理者にお問い合わせください。"
      redirect_to new_user_registration_path
    end
  end


end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/views/user/comments/_comment.html.erb
<div class="card" id="post-comment-<%= comment.id %>">
  <div class="card-body">
    <div class="d-flex align-items-center">
      <%= image_tag comment.user.get_profile_image, size: '30x30', class: "rounded-circle mr-2" %>
      <p class="comment-user-name mb-0 flex-grow-1">
        <% if comment.user == current_user %>
          <%= link_to comment.user.name, my_page_path, class: "text-dark" %>
        <% else %>
          <%= link_to comment.user.name, user_path(comment.user), class: "text-dark" %>
        <% end %>
      </p>
      <% if comment.best_answer %>
        <span class="badge badge-success ml-2">ベストアンサー</span> 
      <% end %>
    </div>
    <div class="mt-2" style="word-break: break-word;">
      <p class="mb-0"><%= comment.content %></p>
    </div>
    <div class="d-flex justify-content-between align-items-center mt-2">
      <small class="text-muted"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></small>
      <div>
        <% if @post.user == current_user && comment.user != current_user %>
          <% if comment.best_answer %>
            <%= link_to 'ベストアンサーを解除', unmark_best_answer_post_comment_path(@post, comment), method: :patch, class: 'btn btn-sm btn-outline-warning', data: { confirm: '本当にこのベストアンサーを解除しますか？' } %>
          <% else %>
            <%= link_to 'ベストアンサーに設定', mark_best_answer_post_comment_path(@post, comment), method: :patch, class: 'btn btn-sm btn-outline-success', data: { confirm: '本当にこのコメントをベストアンサーにしますか？' } %>
          <% end %>
        <% end %>
        <% unless comment.best_answer %>
          <% if comment.user == current_user %>
            <!-- 編集リンク -->
            <%= link_to "編集", edit_post_comment_path(post, comment), class: "btn btn-sm btn-outline-primary mr-2" %>
            <!-- 削除リンク -->
            <%= link_to "削除", post_comment_path(post, comment), method: :delete, remote: true, data: { confirm: "本当に削除しますか？" }, class: "btn btn-sm btn-outline-danger" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/comments/_comment_form.html.erb
<div class="mt-4 mx-auto" style="max-width: 600px;">
  <% unless @post.best_answer? %>
    <%= form_with model: [post, comment], url: post_comments_path(post), local: false, class: "form-inline" do |f| %>
      <div class="form-group w-100 mb-3">
        <%= f.text_area :content, rows: '3', placeholder: "コメントをここに(300字まで)", class: "form-control w-100", id:"commentarea", maxlength: 300 %>
      </div>
      <div class="form-group w-100 text-right">
        <%= f.submit "送信する", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% else %>
    <p>この質問にはベストアンサーが設定されています。これ以上コメントを追加することはできません。</p>
  <% end %>
</div>

app/views/user/comments/create.js.erb
$('#post-comments').append("<%=j render 'user/comments/comment', post: @post, comment: @comment %>");
$('#commentarea').val("");
$('#comment-count').text(<%= @post.comments.size %>);

app/views/user/comments/destroy.js.erb
$('#post-comment-<%= @comment.id %>').remove();
$('#comment-count').text(<%= @post.comments.size %>);
$("#comment_<%= @comment.id %>").fadeOut();

app/views/user/comments/edit.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="mb-4">コメントを編集する</h2>
      <%= form_with model: @comment, url: post_comment_path(@post, @comment), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :content, "コメント内容" %>
          <%= f.text_area :content, rows: 5, class: "form-control", placeholder: "ここにコメントを入力してください" %>
        </div>
        <%= f.submit "更新する", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/user/comments/error.js.erb
alert("コメントの追加に失敗しました。コメントできるのは300文字までです。");

app/views/user/comments/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h3 class="mb-4">すべてのコメント</h3>
      <div id="post-comments-container">
        <div id="post-comments">
          <% @comments.each do |comment| %>
            <div class="card" id="post-comment-<%= comment.id %>" data-comment-id="<%= comment.id %>">
              <div class="card-body">
                <div class="comment-user-info">
                  <div class="comment-user-image">
                    <%= image_tag comment.user.get_profile_image, size: '30x30', class: "rounded-circle" %>
                  </div>
                  <div class="flex-grow-1">
                    <p class="comment-user-name"><%= link_to comment.user.name, "/my_page?id=#{comment.user.id}", class: "text-dark" %></p>
                  </div>
                </div>
                <div class="mt-2" style="word-break: break-word;">
                  <p class="mb-0"><%= comment.content %></p>
                </div>
                <div class="d-flex justify-content-between align-items-center mt-2">
                  <small class="text-muted"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></small>
                  <% if comment.user == current_user %>
                    <div>
                      <%= link_to "編集", edit_post_comment_path(@post, comment), class: "btn btn-sm btn-outline-primary mr-2" %>
                      <%= link_to "削除", post_comment_path(@post, comment), method: :delete, remote: true, data: { confirm: "本当に削除しますか？" }, class: "btn btn-sm btn-outline-danger" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <div class="row">
            <!-- Pagination -->
            <div class="col text-center m-3">
              <nav class="paginate" aria-label="Page navigation">
                <ul class="pagination">
                  <li class="page-item">
                    <%= link_to_prev_page @comments, '<span aria-hidden="true">«</span>'.html_safe, class: "page-link", aria: { label: "Previous" } %>
                  </li>
                  <% @comments.total_pages.times do |i| %>
                    <li class="page-item <%= 'active' if @comments.current_page == i + 1 %>">
                      <%= link_to (i + 1).to_s, url_for(page: i + 1), class: "page-link" %>
                    </li>
                  <% end %>
                  <li class="page-item">
                    <%= link_to_next_page @comments, '<span aria-hidden="true">»</span>'.html_safe, class: "page-link", aria: { label: "Next" } %>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
        <%= link_to "投稿詳細に戻る", post_path(@post), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/user/comments/update.js.erb
$('#comment-buttons-<%= @post.id %>').html("<%= j(render partial: 'user/comments/comment', locals: { post: @post }) %>");